# consts
ALL_PACK_INFO_JSON = "consts/packInfo.json"
DECKLIST_FOLDER = "decklists"

CARD_IMGS_FOLDER = "output/card_imgs"
CARD_IMGS_FOLDER_HALL_OF_HEROES = "output/card_imgs/med_rez"

CARD_INFO_FOLDER = "output/card_info"
DECK_IMGS_FOLDER = "output/deck_imgs"
ALL_CARD_INFO_JSON = f"{CARD_INFO_FOLDER}/all_card_info.json"

# Page dimensions
CARD_WIDTH_INCHES = 2.5
CARD_HEIGHT_INCHES = 3.5

PAGE_WIDTH_INCHES = 8.5
PAGE_HEIGHT_INCHES = 11

PAGE_X_MARGIN_INCHES = 0.4
PAGE_Y_MARGIN_INCHES = 0.1

PRINTABLE_X_SPACE_INCHES = (PAGE_WIDTH_INCHES - (2 * PAGE_X_MARGIN_INCHES))
PRINTABLE_Y_SPACE_INCHES = (PAGE_HEIGHT_INCHES - (2 * PAGE_Y_MARGIN_INCHES))

# Page resolution
PDF_PRINTABLE_DPI = 300
PDF_DIGITAL_DPI = 72
PDF_DOWNSCALE_PECENTAGE = (PDF_DIGITAL_DPI/PDF_PRINTABLE_DPI)

CARD_WIDTH_PX = int(CARD_WIDTH_INCHES * PDF_PRINTABLE_DPI)
CARD_HEIGHT_PX = int(CARD_HEIGHT_INCHES * PDF_PRINTABLE_DPI)

PAGE_WIDTH_PX = int(PAGE_WIDTH_INCHES * PDF_PRINTABLE_DPI)
PAGE_HEIGHT_PX = int(PAGE_HEIGHT_INCHES * PDF_PRINTABLE_DPI)

PAGE_X_MARGIN_PX = int(PAGE_X_MARGIN_INCHES * PDF_PRINTABLE_DPI)
PAGE_Y_MARGIN_PX = int(PAGE_Y_MARGIN_INCHES * PDF_PRINTABLE_DPI)

# Wait for command args to calculate spacer
CARD_X_SPACER_INCHES = None
CARD_Y_SPACER_INCHES = None

CARD_X_SPACER_PX = None
CARD_Y_SPACER_PX = None

# Wait for command args to calculate cards per page
CARD_ROWS_PER_PAGE = None
CARD_COLS_PER_PAGE = None

CAN_CARDS_FIT_ON_PAGE = None 
CARDS_PER_PAGE = None

def initConfig(card_spacers=True, debug_logs=False):
    global CARD_X_SPACER_INCHES
    global CARD_Y_SPACER_INCHES

    global CARD_X_SPACER_PX
    global CARD_Y_SPACER_PX

    global CARD_ROWS_PER_PAGE
    global CARD_COLS_PER_PAGE

    global CARDS_PER_PAGE

    CARD_X_SPACER_INCHES = 0.1 if card_spacers else 0
    CARD_Y_SPACER_INCHES = 0.1 if card_spacers else 0

    CARD_X_SPACER_PX = int(CARD_X_SPACER_INCHES * PDF_PRINTABLE_DPI)
    CARD_Y_SPACER_PX = int(CARD_Y_SPACER_INCHES * PDF_PRINTABLE_DPI)

    # Calculate cards per page; multi-step process
    CARD_ROWS_PER_PAGE = 0
    CARD_COLS_PER_PAGE = 0

    CAN_CARDS_FIT_ON_PAGE = False 
    if PRINTABLE_Y_SPACE_INCHES >= CARD_HEIGHT_INCHES and PRINTABLE_X_SPACE_INCHES >= CARD_WIDTH_INCHES:
        CAN_CARDS_FIT_ON_PAGE = True

    if CAN_CARDS_FIT_ON_PAGE:
        # subtract one spacer instance bc last card has no spacer
        CARD_ROWS_PER_PAGE = 1 + int((PRINTABLE_Y_SPACE_INCHES-CARD_HEIGHT_INCHES) / (CARD_HEIGHT_INCHES + CARD_Y_SPACER_INCHES))
        CARD_COLS_PER_PAGE = 1 + int((PRINTABLE_X_SPACE_INCHES-CARD_WIDTH_INCHES) / (CARD_WIDTH_INCHES + CARD_X_SPACER_INCHES))
    CARDS_PER_PAGE = CARD_ROWS_PER_PAGE * CARD_COLS_PER_PAGE

    # Log page dimensions
    if debug_logs:
        print(f"Cards per page: {CARD_COLS_PER_PAGE}x{CARD_ROWS_PER_PAGE}")

        LEFTOVER_X_SPACE = PRINTABLE_X_SPACE_INCHES - (CARD_COLS_PER_PAGE*CARD_WIDTH_INCHES) - ((CARD_COLS_PER_PAGE-1)*CARD_X_SPACER_INCHES)
        LEFTOVER_Y_SPACE = PRINTABLE_Y_SPACE_INCHES - (CARD_ROWS_PER_PAGE*CARD_HEIGHT_INCHES) - ((CARD_ROWS_PER_PAGE-1)*CARD_Y_SPACER_INCHES)
        print(f"leftover space x: {round(LEFTOVER_X_SPACE, 3)}")
        print(f"leftover space y: {round(LEFTOVER_Y_SPACE, 3)}")
